---
- name: Install helm and run charts
  block:
    - name: "Install apt-transport-https"
      ansible.builtin.package:
        name: apt-transport-https
        state: present

    - name: "Add key for helm repo"
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        keyring: /usr/share/keyrings/helm.gpg

    - name: "Get architecture"
      ansible.builtin.command: dpkg --print-architecture
      register: system_arch
      changed_when: false
      check_mode: false

    - name: "Add helm repo"
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ system_arch.stdout }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
        filename: helm-stable-debian

    - name: "Install helm"
      ansible.builtin.package:
        name: helm
        state: present

    - name: "Add mysql-operator helm repo"
      ansible.builtin.command: helm repo add mysql-operator https://mysql.github.io/mysql-operator/

    - name: "Update cache of mysql-operator helm repo"
      ansible.builtin.command: helm repo update

    - name: "Deploy mysql operator via helm chart"
      kubernetes.core.helm:
        name: mysql-operator
        chart_ref: mysql-operator/mysql-operator
        namespace: mysql-operator
        create_namespace: true
  run_once: true
