---
- name: Install Kubernetes via Kubespray
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  become: true
  vars:
    override_system_hostname: false

- name: Install MySQL
  become: true
  hosts: all
  roles:
    - { role: "mysql-cluster", tags: ["mysql-cluster"] }
